version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: miusuario
      MYSQL_PASSWORD: pollito90@Locochon
      MYSQL_DB: GamesCollector
    depends_on:
      - mysql
    command: sh -c "sleep 30 && flask run --host=0.0.0.0 --port=3000"
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "!myFather7070James^"
      MYSQL_USER: miusuario
      MYSQL_PASSWORD: pollito90@Locochon
      MYSQL_DATABASE: GamesCollector
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
